[package]
name = "aoj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "dsl1a"
path = "src/dsl-1a.rs"

[[bin]]
name = "dsl2c"
path = "src/dsl-2c.rs"